### ISSUE TITLE
CBORObject.GetByteString() report exception on the variable that before has worked fine.

### ISSUE THREAD

**Issue by jojo2234** [peteroupc/CBOR-Java#19] opened 2021-09-09 11:26 UTC
Hello, I am on Kotlin but the exception is in Java, I have a function that get in input a ByteArray object. I convert this object in a CBORObject with `var message = CBORObject.DecodeFromBytes(decompressed)` then I convert an element in this object in ByteArray using `var rgb = message[0].GetByteString()` and everything works fine but when I try to convert the same object in a conditional in the same function just a bit below, I get this exception that report **IllegalStateException: Not a byte String**
Here's the code of my function:
```
private fun CoseData.encodeCose(decompressed: ByteArray): ByteArray {
    var messageObject = CBORObject.DecodeFromBytes(decompressed);
    val rgb = messageObject[0].GetByteString();
    val key = HeaderKeys.KID.AsCBOR();
    messageObject.RemoveAt(2);
    if (CBORObject.DecodeFromBytes(rgb).keys.contains(key)) {
        var ptb = messageObject[0].GetByteString();
    }
    messageObject.Insert(2,this.cbor);
    return messageObject.EncodeToBytes();
}
```

**Comment by peteroupc** [comment] 2021-09-09 13:32
I could not reproduce the problem.  You should include a minimal failing example of the code, including a _minimal_ (smallest possible) input that causes your failure.

**Comment by jojo2234** [comment] 2021-09-09 13:58
Ok, in this moment I can't reproduce the error too, now I get another exception on a piece of code that before was working. I don't have made any change in the input or in code. I've only closed Android Studio and put the PC in standby mode and now I open it and the exception is changed, now I don't think the issue it's related to your source code. The new exception is on `messageObject[0].Set(key,this.kid);` and say: **Not a map or array**.  Here is the code: https://github.com/jojo2234/GreenPass-Experiments/blob/main/GettingUp.kt

**Comment by peteroupc** [comment] 2021-09-09 14:55
I'm sorry, it appears this is in connection to a suspicious project and helping you further would not be in my interest.  Thus, I will close this topic.

**Closed by peteroupc** 2021-09-09 14:55 UTC
